version: '3'
services:
  pyrocdn_mail:
    container_name: pyrocdn-mail-service
       build:
         context: .
         dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./src:/src